services:
  controller:
    build: ./controller
    container_name: controller
    hostname: controller
    volumes:
      - ./shared-ssh:/shared
      - ./ansible:/ansible
      - ./controller/ssh:/root/.ssh
    networks:
      - ansible-net

  slave1:
    build: ./slave
    container_name: slave1
    hostname: slave1
    volumes:
      - ./shared-ssh:/shared
    networks:
      - ansible-net

  slave2:
    build: ./slave
    container_name: slave2
    hostname: slave2
    volumes:
      - ./shared-ssh:/shared
    networks:
      - ansible-net

networks:
  ansible-net:
    driver: bridgie
