FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y --no-install-recommends openssh-client git iputils-ping python3 python3-pip && pip3 install ansible && apt-get clean && rm -rf /var/lib/apt/lists/*

USER jenkins
